# Generated by Django 3.0.2 on 2020-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200421_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='uploaded_images', verbose_name='imagey boi'),
        ),
    ]
