# Generated by Django 3.0.2 on 2020-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200421_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/projects', verbose_name='imagey boi'),
        ),
    ]
