# Generated by Django 3.0.2 on 2020-04-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200421_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/img/projects', verbose_name='imagey boi'),
        ),
    ]
